### ISSUE TITLE
problem following examples in Readme.md

### ISSUE THREAD

**Issue by silviaegt** [dracor-org/rdracor#7]
Hi again @Pozdniakov, @lehkost, and @cmil,

I tried following the instructions in ["Plays in the corpus"](https://github.com/dracor-org/rdracor#plays-in-the-corpus)
However when I tried this:

`ru <- get_corpus(corpus = "rus")`
I got:

```
>summary(ru)
Error in Summary.factor(c(53L, 56L, NA, 54L, 50L, 52L, 53L, 51L, 83L,  : 
  ‘range’ not meaningful for factors
```

I tried with another language and did:

`ru <- get_corpus(corpus = "span")`

And got, as expected:

```
> summary(es)
No information on written years	
Premiere years (range): 1895 - 1970	
Years of the first printing (range): 1878 - 1945	
25 plays in Spanish Drama Corpus	
Corpus id: span, repository: https://github.com/dracor-org/spandracor
```

However when I tried retrieving the authors, I got this:

```
> es_au <- authors(es)
Error in data.table::rbindlist(corpus$authors) : 
  Item 12 has 5 columns, inconsistent with item 1 which has 4 columns. To fill missing columns use fill=TRUE.
```

Thanks in advance for any help you can give me!

**Comment by Pozdniakov** [comment]
Hi, @silviaegt! 

The function `authors()` is somewhat deprecated for now. Originally, I tried to solve the problem that authors field breaks the flat structure of the corpus data: some plays have several authors. However, I decided to avoid using special just for that, and came with the following solution. 

There are columns for the first author (short name, full name, key) and [list column (nested columns)](https://tidyr.tidyverse.org/articles/nest.html) for all authors. In the most corpora you can just use firstAuthor (because there are no more than one author), but there are at least two exceptions for now: German corpus and Swedish Corpus. 

I will definitely rewrite the ReadMe for the new version
